parameters:
- name: project
  displayName: 'Project'
  type: string

jobs:
- job: ${{ parameters.project }}
  displayName: Run measurements for ${{ parameters.project }}
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Run measurements
    inputs:
      command: 'run'
      arguments: '--configuration Release'
      projects: |
        Resources/TgRl/WinTimers/WinTimers/${{ parameters.project }}/${{ parameters.project }}.csproj
        
  - task: PowerShell@2
    displayName: Collect deltas
    inputs:
      targetType: 'inline'
      script: |
        New-Item -Path "$(Pipeline.Workspace)" -Name "Deltas" -ItemType "directory"
        Copy-Item -Path "Resources/TgRl/WinTimers/WinTimers/${{ parameters.project }}/bin/Release/net5.0/deltas_*.txt" -Destination "$(Pipeline.Workspace)/Deltas"
        
  - task: PublishPipelineArtifact@1
    displayName: Publish 'Deltas' artifact
    inputs:
      targetPath: '$(Pipeline.Workspace)/Deltas'
      artifactName: 'Deltas_${{ parameters.project }}'
      artifactType: pipeline